// <auto-generated />
using System;
using Check24.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Check24.Db.Migrations
{
    [DbContext(typeof(Check24Context))]
    [Migration("20240413231612_changedpk")]
    partial class changedpk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Check24.Core.Entities.Bet", b =>
                {
                    b.Property<Guid>("BetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AwayTeamGoals")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BetTimestamp")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HomeTeamGoals")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BetId")
                        .HasName("PK__Bets__454024890E793E80");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("Check24.Core.Entities.Community", b =>
                {
                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommunityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CommunityId")
                        .HasName("PK__Communit__CCAA5B69291F2E5F");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("Check24.Core.Entities.Game", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("GameDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("GameStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GameId")
                        .HasName("PK__Games__2AB897FDE4264D3A");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Check24.Core.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CEE4C52B1");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Check24.Core.Entities.UserCommunity", b =>
                {
                    b.Property<Guid>("UserCommunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserCommunityId")
                        .HasName("PK__UserComm__3781934CA42845C8");

                    b.HasIndex("CommunityId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCommunities");
                });

            modelBuilder.Entity("Check24.Core.Entities.Bet", b =>
                {
                    b.HasOne("Check24.Core.Entities.Game", "Game")
                        .WithMany("Bets")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK__Bets__GameId__70DDC3D8");

                    b.HasOne("Check24.Core.Entities.User", "User")
                        .WithMany("Bets")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Bets__UserId__6FE99F9F");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Check24.Core.Entities.UserCommunity", b =>
                {
                    b.HasOne("Check24.Core.Entities.Community", "Community")
                        .WithMany("UserCommunities")
                        .HasForeignKey("CommunityId")
                        .HasConstraintName("FK__UserCommu__Commu__619B8048");

                    b.HasOne("Check24.Core.Entities.User", "User")
                        .WithMany("UserCommunities")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__UserCommu__UserI__60A75C0F");

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Check24.Core.Entities.Community", b =>
                {
                    b.Navigation("UserCommunities");
                });

            modelBuilder.Entity("Check24.Core.Entities.Game", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("Check24.Core.Entities.User", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("UserCommunities");
                });
#pragma warning restore 612, 618
        }
    }
}
